name: risuai

services:
  risuai:
    container_name: risuai
    image: ghcr.io/kwaroran/risuai:latest
    restart: always
    ports:
      - 6002:6002
    volumes:
      - risuai-data:/app/data

volumes:
  risuai-data:
